### ISSUE TITLE
建议是连数据库

### ISSUE THREAD

**Issue by TheSorry404** [Xuanzai20060206/EZGame#2]
你这是fork的项目吧？
可以租一台小型的服务器跑网页和数据库啊 连一下数据库把排行榜跑起来啊
还有就是你这个昵称容易被校领导盯上 注意点

**Comment by Xuanzai20060206** [comment]
非常感谢兄弟的指点！！！
也很意外，你能通过那个二维码找到我的github，不妨留个微信
咱俩深♂入♂探♂究♂一下

**Comment by TheSorry404** [comment]
QQ吧 1014010594
虽然也不是很懂技术就是了

顺便 你是本部还是精致？

**Comment by TheSorry404** [comment]
啥二维码 我是朋友圈里看到你fork的项目的action link顺着找过来的hhhh

**Comment by Xuanzai20060206** [comment]
精致，兄弟你也二中？

**Comment by TheSorry404** [comment]
居然也是精致吗 草

**Comment by Xuanzai20060206** [comment]
哈哈哈哈哈哈
一个《也》
说出多少共鸣哈哈哈哈哈

**Comment by TheSorry404** [comment]
//叹气  
只能说波波子的形象树立得成功

**Comment by Xuanzai20060206** [comment]
确实，据说我这个项目，已经在吉大，师大，市实验，省实验等一系列高中传开了。。。
就怕开学第一天
“记大过”
btw：兄弟你高一高二呀

**Comment by TheSorry404** [comment]
高二  

听说了哈哈哈哈哈
刚才还和初中同学吹水说要给他们市二整一个呢 没素材最后就算了
主要是你这个换的太好笑了hhhhh

记大过不至于吧 总不能按照生日追查谁做的
那也太可怕

**Comment by Xuanzai20060206** [comment]
哈哈哈哈哈但愿如此叭，你要是需要最初的源码的话，我发给你，或者你把我这个项目download一下，你给他们改着玩吧哈哈哈哈哈哈
本来现在初高中生用github的就少
能在这上头遇到你也是挺巧的一个事哈哈哈哈哈哈
btw：学长好，我是精致高一学生会网络组的一员

**Comment by TheSorry404** [comment]
不用 源码项目我知道

这些外网东西了解的人少很正常 其实越少越好
学生会没太大兴趣申请 好麻烦感觉（
没细研究过哪个语言或者项目 也觉得自己没什么资格参与那些事
作罢了 啥也不精通 当个咸鱼也挺好

**Comment by Xuanzai20060206** [comment]
哈哈哈哈哈哈一样的，我也是
之前报学生会也就是个兴趣

**Comment by TheSorry404** [comment]
QQ聊吧
issue是公开的 聊多了透露身份不太好
